Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,9 +20,13 @@ jobs:
       run: |
         mkdir -p ~/openwrt
         cd ~/openwrt
-        wget https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
+        wget -q --show-progress https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
+        if [ ! -f openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz ]; then
+          echo "SDK download failed!"
+          exit 1
+        fi
         tar -xf openwrt-sdk-*.tar.xz
-        mv openwrt-sdk-* sdk
+        mv openwrt-sdk-23.05.3-x86-64* sdk
 
     - name: Prepare QModem Package
       run: |
